---
## JetBrains Mono Font
- name: Configure fonts - Interface Text
  dconf:
    key: "/org/gnome/desktop/interface/font-name"
    value: "'JetBrains Mono Bold 11'"
    state: present

- name: Configure fonts - Document Text
  dconf:
    key: "/org/gnome/desktop/interface/document-font-name"
    value: "'JetBrains Mono Regular 9'"
    state: present

- name: Configure fonts - Monospace Text
  dconf:
    key: "/org/gnome/desktop/interface/monospace-font-name"
    value: "'JetBrains Mono Regular 9'"
    state: present

- name: Configure fonts - Window Title
  dconf:
    key: "/org/gnome/desktop/wm/preferences/titlebar-font"
    value: "'JetBrains Mono Regular 11'"
    state: present
