---
code_executable: "/snap/bin/code"
code_extensions:
  ## Ansible, Docker-Compose, etc.
  - redhat.vscode-yaml

  ## Jupyter
  - ms-toolsai.jupyter

  ## Terraform
  - hashicorp.terraform

  ## Docker and Remote Development
  - ms-azuretools.vscode-docker
  - ms-vscode-remote.remote-containers
  - ms-vscode-remote.remote-ssh
  - ms-vscode-remote.remote-ssh-edit
  # - ms-vscode-remote.remote-wsl
  - ms-vscode-remote.vscode-remote-extensionpack

  ## General Development
  - christian-kohler.path-intellisense
  - vscode-icons-team.vscode-icons
  - riccardoNovaglia.missinglineendoffile
  - shardulm94.trailing-spaces
  # - Shan.code-settings-sync

  ## Git Utilities
  - eamodio.gitlens
  - donjayamanne.githistory
  - mhutchie.git-graph

  ## Markdown Linting
  - DavidAnson.vscode-markdownlint

  ## Python Development
  - ms-python.python
  - himanoa.Python-autopep8
  - njpwerner.autodocstring
  - wholroyd.jinja
  # Pyright Attribution to tiangolo and florimondmanca
  # https://twitter.com/tiangolo/status/1252891149708275713?s=21
  # > Disabled type checking in the extension settings as I rely on mypy,
  # > but autoimport and unused import colouring alone make it a
  # > 100% worthwhile companion on VSCode
  - ms-pyright.pyright
  - ms-python.vscode-pylance

  ## Spellchecking
  - streetsidesoftware.code-spell-checker

  ## Themes
  - sdras.night-owl

  ## Travis-CI
  # - felixrieseberg.vsc-travis-ci-status # has issues with status resolution

  ## Vue.js Development
  - octref.vetur
  - dbaeumer.vscode-eslint
  - pranaygp.vscode-css-peek
  - sdras.vue-vscode-snippets

docker_compose_version: 1.29.2

# nautilus_mounts:
#   - mount: "folder"
#     unc_path: "\\\\server\\folder\\"  # escaped slashes

flatpak_applications:
  #- "com.giuspen.cherrytree"
  - "com.uploadedlobster.peek"
  # - "com.github.alainm23.planner" # not used
  # - "com.valvesoftware.Steam"
  - "org.kde.okular"
  #- "org.libreoffice.LibreOffice"
  - "com.github.junrrein.PDFSlicer"

# Dash to Dock Settings
gnome_dash_to_dock_preferences:
# Apply Custom Theme
  - key: "/org/gnome/shell/extensions/dash-to-dock/apply-custom-theme"
    value: "true"
  # Custom Background Color
  - key: "/org/gnome/shell/extensions/dash-to-dock/custom-background-color"
    value: "false"
  # Custom Theme Customize Running Dots
  - key: "/org/gnome/shell/extensions/dash-to-dock/custom-theme-customize-running-dots"
    value: "true"
  # Custom Theme Running Dots Color
  - key: "/org/gnome/shell/extensions/dash-to-dock/custom-theme-running-dots-color"
    value: "'#729fcf'"
  # Custom Theme Shrink
  - key: "/org/gnome/shell/extensions/dash-to-dock/custom-theme-shrink"
    value: "true"
  # Dock Fixed
  - key: "/org/gnome/shell/extensions/dash-to-dock/dock-fixed"
    value: "'false'"
  # Dock Position BOTTOM
  - key: "/org/gnome/shell/extensions/dash-to-dock/dock-position"
    value: "'BOTTOM'"
  # Extend Height
  - key: "/org/gnome/shell/extensions/dash-to-dock/extend-height"
    value: "true"
  # Force Straight Corner
  - key: "/org/gnome/shell/extensions/dash-to-dock/force-straight-corner"
    value: "false"
  # Icon Size Fixed
  - key: "/org/gnome/shell/extensions/dash-to-dock/icon-size-fixed"
    value: "true"
  # Icon Size
  - key: "/org/gnome/shell/extensions/dash-to-dock/dash-max-icon-size"
    value: "24"
  # Intellihide Mode
  - key: "/org/gnome/shell/extensions/dash-to-dock/intellihide-mode"
    value: "'ALL_WINDOWS'"
  # Intellihide Status
  - key: "/org/gnome/shell/extensions/dash-to-dock/intellihide"
    value: "'false'"
  # Isolate Workspaces
  - key: "/org/gnome/shell/extensions/dash-to-dock/isolate-workspaces"
    value: "true"
  # Show Apps at Top
  - key: "/org/gnome/shell/extensions/dash-to-dock/show-apps-at-top"
    value: "true"
  # Unity Backlit Items
  - key: "/org/gnome/shell/extensions/dash-to-dock/unity-backlit-items"
    value: "false"
  # Transparency Mode
  - key: "/org/gnome/shell/extensions/dash-to-dock/transparency-mode"
    value: "'FIXED'"
  # Running Indicator Style
  - key: "/org/gnome/shell/extensions/dash-to-dock/running-indicator-style"
    value: "'SEGMENTED'"
  # 0.7 always converts to 0.69999999999999996, due to the Double data type
  # Background Opacity
  - key: "/org/gnome/shell/extensions/dash-to-dock/background-opacity"
    value: "0.69999999999999996"
  # Enable Multi-Monitor Docks
  - key: "/org/gnome/shell/extensions/dash-to-dock/multi-monitor"
    value: "false"
  # Pressure Threshold
  - key: "/org/gnome/shell/extensions/dash-to-dock/pressure-threshold"
    value: "0.0"

gnome_keybindings:
  # Window and Application switching
  - key: "/org/gnome/desktop/wm/keybindings/switch-applications"
    value: "['<Super>Tab']"
  - key: "/org/gnome/desktop/wm/keybindings/switch-applications-backward"
    value: "['<Shift><Super>Tab']"
  - key: "/org/gnome/desktop/wm/keybindings/switch-windows"
    value: "['<Alt>Tab']"
  - key: "/org/gnome/desktop/wm/keybindings/switch-windows-backward"
    value: "['<Shift><Alt>Tab']"
  # Move windows (<Ctrl><Alt>Direction interferes and wasn't reliable)
  - key: "/org/gnome/desktop/wm/keybindings/move-to-monitor-down"
    value: "['<Shift><Alt>Down']"
  - key: "/org/gnome/desktop/wm/keybindings/move-to-monitor-up"
    value: "['<Shift><Alt>Up']"
  - key: "/org/gnome/desktop/wm/keybindings/move-to-monitor-left"
    value: "['<Shift><Alt>Left']"
  - key: "/org/gnome/desktop/wm/keybindings/move-to-monitor-right"
    value: "['<Shift><Alt>Right']"
    # Move workspaces
  - key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-down"
    value: "['<Shift><Super>Down']"
  - key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-up"
    value: "['<Shift><Super>Up']"
  - key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-left"
    value: "['<Shift><Super>Left']"
  - key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-right"
    value: "['<Shift><Super>Right']"
  - key: "/org/gnome/desktop/wm/keybindings/move-to-workspace-last"
    value: "['<Shift><Super>End']"
    # Close Windows (added '<Super>w')
  - key: "/org/gnome/desktop/wm/keybindings/close"
    value: "['<Super>w','<Alt>F4']"
    # Launch Terminal (added '<Super>t')
  - key: "/org/gnome/settings-daemon/plugins/media-keys/terminal"
    value: "['<Ctrl><Alt>t']"
    # Lock Screen
  - key: "/org/gnome/settings-daemon/plugins/media-keys/screensaver"
    value: "['<Super>l']"

gnome_preferences:
  # Better Font Smoothing
  - key: "/org/gnome/settings-daemon/plugins/xsettings/antialiasing"
    value: "'rgba'"
  # Desktop Usability improvements
  # Mouse Acceleration Profile
  - key: "/org/gnome/desktop/peripherals/mouse/accel-profile"
    value: "'adaptive'"
  # Allow volume above 100%
  - key: "/org/gnome/desktop/sound/allow-volume-above-100-percent"
    value: "true"
  # Calendar Show Week Date
  - key: "/org/gnome/desktop/calendar/show-weekdate"
    value: "true"
  # Show Date in Clock
  - key: "/org/gnome/desktop/interface/clock-show-date"
    value: "true"
  # Nautilus - Clock Format
  - key: "/org/gnome/desktop/interface/clock-format"
    value: "'24h'"
  # Resize with right button
  - key: "/org/gnome/desktop/wm/resize-with-right-button"
    value: "true"
  # Button Layout
  - key: "/org/gnome/desktop/wm/button-layout"
    value: "'appmenu:minimize,maximize,close'"
  # Focus Mode
  - key: "/org/gnome/desktop/wm/preferences/focus-mode"
    value: "'sloppy'"
  # Desktop Icons
  - key: "/org/gnome/desktop/background/show-desktop-icons"
    value: "false"
  # Nautilus (File Manager) Usability
  # Nautilus - Default Zoom Level
  - key: "/org/gnome/nautilus/icon-view/default-zoom-level"
    value: "'standard'"
  # Nautilus - Executable Text Activation
  - key: "/org/gnome/nautilus/preferences/executable-text-activation"
    value: "'ask'"
  # Nautilus - Sort Directories
  - key: "/org/gtk/Settings/FileChooser/sort-directories-first"
    value: "true"
  # Nautilus - User Tree View
  - key: "/org/gnome/nautilus/list-view/use-tree-view"
    value: "true"
  # Shell - Attach Modal Dialogues
  - key: "/org/gnome/shell/overrides/attach-modal-dialogs"
    value: "false"
  # Shell Overrides
  # Workspaces Only on Primary
  - key: "/org/gnome/shell/overrides/workspaces-only-on-primary"
    value: "false"

nodejs_version: "14.x"
nodejs_npm_global_packages:
  - name: "yarn"
  - name: "@vue/cli"
  - name: "markdownlint-cli"

snaps_chat:
  - name: "signal-desktop"
  - name: "telegram-desktop"
  - name: "slack"
    classic: "yes"
snaps_common:
  - name: "snap-store"
  - name: "flameshot"
  - name: "breaktimer"
  - name: "drawio"
  # https://github.com/jgraph/drawio-desktop/issues/138,
  # snap 12.6.5 > flatpak 12.4 (as of 2020-02-28)
  - name: "spotify"
  - name: "ncspot"
  - name: "authy"
    channel: "beta"
snaps_development:
  - name: "postman"
  # - "codium" # Code without telemetry
  - name: "sublime-text"
    classic: "yes"
snaps_web_browsers:
  - name: "chromium"
  # - name: "firefox" # Using deb until gnome-extensions installations work with firefox snap
snaps_web_browsers_plugs:
  - plug: "home"
    app: "chromium"

stacer_version: 1.1.0

yadm_dotfiles_repo: "https://github.com/iancleary/dotfiles"
yadm_dotfiles_branch: "main"

# https://github.com/iancleary/ansible-role-zsh
zsh_theme: robbyrussell
zsh_custom_shell_command: "false"
# useful when users are bound to external systems (i.e. active directory)
# zsh_custom_shell_command: "true"
# zsh_default_shell_command: "/opt/pbis/bin/config LoginShellTemplate /usr/bin/zsh"
zsh_aliases:
  # https://opensource.com/article/19/7/bash-aliases
  - ls='ls -F'
  - ll='ls -lh'
  - mnt="mount | awk -F' ' '{ printf \"%s\t%s\n\",\$1,\$3; }' | column -t | egrep ^/dev/ | sort"
  - hg='history|grep' # search bash history
  - left='ls -t -1' # most recently edited files
  - cg='cd `git rev-parse --show-toplevel`' # go to git main level
ohmyzsh_bundles:
  # Bundles from the default repo (robbyrussell's oh-my-zsh) only need a name
  # https://github.com/ohmyzsh/ohmyzsh/wiki/Plugins
  #
  # `name` is required (any valid file name will do so long as it's unique for the bundles)
  # `url` is git username/repo
  # `version` is git release and is required if `url` is define
  # - name: ansible
  # - name: aws
  # - name: docker
  # - name: docker-compose
  - name: gitfast
  # - name: pipenv
  - name: yarn
  # Syntax highlighting bundle.
  - name: 'zsh-syntax-highlighting'
    git:
      user: zsh-users
      repo: zsh-syntax-highlighting
      version: 0.7.1
  # # Autosuggestions
  # - name: zsh-autosuggestions # `name` is required (any valid file name will do so long as it's unique for the bundles)
  #   repo:
  #     user: zsh-users
  #     repo: zsh-autosuggestions
  #     version: v0.6.4
  - name: powerlevel10k
    skip_zshrc_plugin:
    git:
      user: romkatv
      repo: powerlevel10k
      version: v1.12.0
