---
- hosts: all
  # connection: local
  vars_files:
    - default.config.yml
  pre_tasks:
    - name: Include playbook configuration.
      include_vars: "{{ item }}"
      with_fileglob:
        - "{{ playbook_dir }}/config.yml"
      tags: ['always']

  roles:
    # 'skip-ci' allows me to not test that role
    # 'never' is a special tag that is on run when that tag is specified

    # Terminal
    - {role: zsh, tags: ['terminal', 'desktop', 'zsh', 'skip-ci']}
    - {role: zsh_fonts, tags: ['terminal', 'desktop', 'fonts']}
    - {role: docker, tags: ['terminal', 'desktop', 'docker', 'skip-ci'], become: true}
    # - {role: python, tags: ['python']}
    - {role: nodejs, tags: ['terminal', 'desktop', 'nodejs', 'npm', 'yarn'], become: true}
    - {role: terraform, tags: ['terminal', 'desktop', 'terraform']}
    - {role: github_cli, tags: ['terminal', 'desktop', 'github-cli']}

    # Dotfiles
    - {role: yadm, tags: ['dotfiles', 'yadm']}

    # Virtual Machine
    - {role: hyper-v, tags: ['vm', 'hyper-v', 'skip-ci']}

    # Desktop
    - {role: app-image, tags: ['desktop', 'app-image']}
    - {role: profile-sync-daemon, tags: ['desktop', 'profile-sync-daemon']}
    - {role: code, tags: ['desktop', 'code']}
    - {role: flatpak, tags: ['desktop', 'flatpak', 'skip-ci']}
    - {role: snapd, tags: ['desktop', 'snapd', 'skip-ci']}
    - {role: nordvpn, tags: ['desktop', 'nordvpn', 'skip-ci']}
    - {role: stacer, tags: ['desktop', 'stacer']}
    - {role: wifi-analyzer, tags: ['desktop', 'wifi-analyzer']}
    - {role: caffeine, tags: ['desktop', 'caffeine']}
    - {role: timeshift, tags: ['desktop', 'timeshift']}
    # Ubuntu 20.04 (Not Fedora -> Pipewire)
    - {role: pulseaudio, tags: ['desktop', 'pulseaudio']}

    # Not desired on elementary OS 6 (dropped desktop tag)
    - {role: gnome-sushi, tags: ['gnome-sushi']}
    - {role: ulauncher, tags: ['ulauncher']}

    # Miscellaneous
    - {role: nautilus-mounts, tags: ['never', 'nautilus-mounts']}
    - {role: standard-notes, tags: ['never', 'common-snaps']}

    # Debug
    - {role: debug, tags: ['debug']}
