---
- name: Install PPA
  become: true
  ansible.builtin.apt_repository:
    repo: ppa:teejee2008/timeshift
    state: present

- name: Install apt package
  become: true
  apt:
    name: "timeshift"
    state: present
    update_cache: "yes"
