---
- import_tasks: setup-nodejs-Debian.yml
  when: ansible_os_family == 'Debian'

- import_tasks: setup-nodejs-RedHat.yml
  when: ansible_os_family == 'RedHat'

- name: Nodejs - Define nodejs_install_user
  set_fact:
    nodejs_install_user: "{{ ansible_user | default(lookup('env', 'USER')) }}"
  when: nodejs_install_user is not defined
  
- name: Create npm global directory
  become: true
  file:
    path: "{{ npm_config_prefix }}"
    owner: "{{ nodejs_install_user }}"
    group: "{{ nodejs_install_user }}"
    state: directory

- name: Add npm_config_prefix bin directory to global $PATH.
  become: true
  template:
    src: npm.sh.j2
    dest: /etc/profile.d/npm.sh
    mode: 0644

- name: Reload Path for npm.sh
  become: true
  shell:
    cmd: ". /etc/profile"
  changed_when: false

- name: Install NPM global packages
  become: true
  community.general.npm:
    name: "{{ item.name | default(item) }}"
    version: "{{ item.version | default('latest') }}"
    global: "yes"
    state: latest
  environment:
    NPM_CONFIG_PREFIX: "{{ npm_config_prefix }}"
    NODE_PATH: "{{ npm_config_prefix }}/lib/node_modules"
    NPM_CONFIG_UNSAFE_PERM: "{{ npm_config_unsafe_perm }}"
  loop: "{{ nodejs_npm_global_packages }}"
  tags: ['skip_ansible_lint']


