---
- name: install dconf-editor
  become: true
  apt:
    name: "dconf-editor"
    state: present

- name: Check Key Existence
  dconf:
    key: "{{ item.key}}"
    state: read
  with_items: "{{ gnome_keybindings }}"

# Window and Application switching
- name: Custom Keybinding Entries
  dconf:
    key: "{{ item.key}}"
    value: "{{ item.value }}"
    state: present
  with_items: "{{ gnome_keybindings }}"
