---
- name: Converge
  hosts: all

  pre_tasks:
    - name: Update apt cache. (Deb)
      apt: update_cache=yes cache_valid_time=600
      when: ansible_os_family == 'Debian'
      changed_when: false

  roles:
    - role: iancleary.yadm
