---
- name: Converge
  hosts: all

  vars:
    nodejs_version: "16.x"
    nodejs_install_npm_user: root
    nodejs_install_npm_group: root
    npm_config_prefix: /root/.npm-global
    npm_config_unsafe_perm: "true"
    nodejs_npm_global_packages:
      - slugify
      - name: jslint
        version: 0.12.0
      - name: yo

  pre_tasks:
    - name: Update apt cache.
      apt: update_cache=true cache_valid_time=600
      when: ansible_os_family == 'Debian'

  roles:
    - role: icancclearynow.nodejs
