---
- name: Docker - install apt package dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
    state: present

- name: Docker - Add Docker's official GPG Key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

# 20.04 has everything needed within Ubuntu's repositories
- name: Docker - Setup Stable Repository 18.04
  ansible.builtin.apt_repository:
    repo: >-
      deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
  when: ansible_distribution_version == "18.04"

- name: Docker - install Docker - 18.04
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    update_cache: "yes"
  when: ansible_distribution_version == "18.04" and ansible_os_family == "Debian"

- name: Docker - install Docker - 20.04 (Ubuntu)
  ansible.builtin.apt:
    name: docker.io
    update_cache: "yes"
  when: ansible_distribution_version == "20.04" and ansible_os_family == "Debian"

- name: Docker - install Docker - 20.04 (elementary OS 6)
  ansible.builtin.apt:
    name: docker.io
    update_cache: "yes"
  when: ansible_distribution_version == "6" and ansible_os_family == "elementary OS"

- name: Docker - Create the docker group
  ansible.builtin.group:
    name: docker
    state: present

- name: Docker - Add users to the group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: ["docker"]
    append: "yes"
  loop: "{{ docker_users|flatten(levels=1) }}"

- name: Docker - Check current docker-compose version.
  ansible.builtin.command: docker-compose --version
  register: docker_compose_current_version
  changed_when: false
  failed_when: false

- name: Docker - Delete existing docker-compose version if it's different.
  ansible.builtin.file:
    path: "{{ docker_compose_path }}"
    state: absent
  when: >
    docker_compose_current_version.stdout is defined
    and docker_compose_version not in docker_compose_current_version.stdout

- name: Docker - Install Docker Compose (if configured).
  ansible.builtin.get_url:
    url: "https://github.com/docker/compose/releases/download/\
          {{ docker_compose_version }}/docker-compose-Linux-x86_64"
    dest: "{{ docker_compose_path }}"
    mode: 0755
